@echo off
set "BasePath=%~dp0"

REM --- This creates a local environment, not modifying the CMD environment ---
SETLOCAL EnableDelayedExpansion

REM --- .bat for deleting generated files, generate vs project files and opening the project in Unreal Editor or Opening the .sln file --- 
REM --- Copyright Zulo Interactive. All Rights Reserved.  --- 
REM --- Authors:  --- 
REM --- Jorge Marin Ferrandiz @spary1144 --- 
REM --- Alonso Moreno Gil @ph0nsy ---

REM --- Variables: ---
REM --- UPROJECT: Path to the .uproject file ---
REM --- UEBuildPath: Path to the UnrealBuildTool.exe file ---
REM --- CONFIGURATION: DebugGame or Development, depending on your choice 
REM --- (Preferable DebugGame, sometimes some IDEs don't let you see some variables in Development) ---
REM --- PLATFORM: Win64 ---
REM --- This wont change normally, but just in case you want to develop for another platform ---
REM --- TARGET: LadyUmbrellaEditor ---
REM --- The target is tipically the name of .uproject + Editor ---

set "UPROJECT=%BasePath%LadyUmbrella.uproject"
set "UEBuildPath=C:\Program Files\Epic Games\UE_5.5\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.exe"

set CONFIGURATION=DebugGame
set PLATFORM=Win64
set TARGET=LadyUmbrellaEditor

echo --- GitBuild.bat ---
echo --- Tool for removing generated files (and more) --- 
echo --- Opening .sln or .uproject ---
echo Current Path:         %BasePath%
echo UnrealBuildTool Path: %UEBuildPath%
echo Project Path:         %UPROJECT%
echo(
echo(
echo --- Are you a programmer? (y/n): ---

set /p RESP=

REM --- This folders/files are tipically auto-generated by Unreal Engine, so we delete them ---

set "folder1=%BasePath%DerivedDataCache"
set "folder2=%BasePath%Intermediate"
set "folder3=%BasePath%Saved"
set "folder4=%BasePath%Binaries"
set "folder5=%BasePath%Build"

echo folder 1: %folder1%
echo folder 2: %folder2%
echo folder 3: %folder3%
echo folder 4: %folder4%
echo folder 5: %folder5%

rd /s /q "%folder1%"
rd /s /q "%folder2%"

REM --- Iterating through the Saved folder and deleting all files and folders except for the Collections and Config folders ---
REM --- Deleting collections might be annoying  

FOR %%a IN ("%folder3%\*") DO ( DEL "%%a" )
FOR /d %%a IN ("%folder3%\*") DO ( 
	IF /i NOT "%%~nxa"=="Collections" (
		IF /i NOT "%%~nxa"=="Config" ( 
			echo Deleting: %%~nxa
			RD /S /Q "%%a" 
		) ELSE (
			FOR /d %%b IN ("%%a\*") DO (
				FOR %%c IN ("%%b\*") DO (
					IF /i NOT "%%~nxc"=="EditorPerProjectUserSettings.ini" (
						echo Deleting file %%~nxc in folder %%~nxb
						DEL "%%c"
					)
				)
				
				FOR /d %%c IN ("%%b\*") DO (
					echo Deleting subfolder: %%~nxc in folder %%~nxb
					RD /S /Q "%%c"
				)
			)
		)
	)
)

rd /s /q "%folder4%"
rd /s /q "%folder5%"
del /F /Q "*.sln"

REM ---- Generate Visual studio project files ----
echo Generating VS project files for %UPROJECT% ...
"%UEBuildPath%" -projectfiles -project="%UPROJECT%" -game -engine

REM ---- Do we want to open the project in Unreal Editor or the .sln file? ----
if /i "%RESP%"=="y" (

    REM ---- Compile project so we don't have to wait for the .sln file to open---- 
    echo Compiling Project...
    
    "%UEBuildPath%" %TARGET% %PLATFORM% %CONFIGURATION% -Project="%UPROJECT%" -Progress -WaitMutex
    for %%f in ("%BasePath%*.sln") do (
    
        REM ---- Opening the .sln file with default application ----
        REM ---- Not using Visual or Rider, just in case someone wants to use other ----
        
        echo Opening %%~nxf ...
        start "" "%%f"
        goto :end
        
    )
) else (

    REM --- This option opens the .uproject file in Unreal Editor ---
    REM --- Right now this only executes if the user answered "n" to the question (Love my design team :) ---
    
    echo Opening Unreal Editor...
    start "" "%UPROJECT%"
)

echo Finished.
REM -- If close the window, uncomment this:
 end
REM -- If not, uncomment this:
REM -- pause
